// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_InterfaceNotFound ErrorCode = 0
	ErrorCode_AccountNotFound   ErrorCode = 1
	ErrorCode_AccountExist      ErrorCode = 2
	ErrorCode_DataNotFound      ErrorCode = 3
	ErrorCode_DataExist         ErrorCode = 4
	ErrorCode_GenUuidFailed     ErrorCode = 5
	ErrorCode_GenShortIdFailed  ErrorCode = 6
	ErrorCode_ServerError       ErrorCode = 7
)

var ErrorCode_name = map[int32]string{
	0: "InterfaceNotFound",
	1: "AccountNotFound",
	2: "AccountExist",
	3: "DataNotFound",
	4: "DataExist",
	5: "GenUuidFailed",
	6: "GenShortIdFailed",
	7: "ServerError",
}

var ErrorCode_value = map[string]int32{
	"InterfaceNotFound": 0,
	"AccountNotFound":   1,
	"AccountExist":      2,
	"DataNotFound":      3,
	"DataExist":         4,
	"GenUuidFailed":     5,
	"GenShortIdFailed":  6,
	"ServerError":       7,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type RedisMessageType int32

const (
	RedisMessageType_SetString RedisMessageType = 0
	RedisMessageType_SetByte   RedisMessageType = 1
	RedisMessageType_GetString RedisMessageType = 2
	RedisMessageType_GetByte   RedisMessageType = 3
	RedisMessageType_Delete    RedisMessageType = 4
)

var RedisMessageType_name = map[int32]string{
	0: "SetString",
	1: "SetByte",
	2: "GetString",
	3: "GetByte",
	4: "Delete",
}

var RedisMessageType_value = map[string]int32{
	"SetString": 0,
	"SetByte":   1,
	"GetString": 2,
	"GetByte":   3,
	"Delete":    4,
}

func (x RedisMessageType) String() string {
	return proto.EnumName(RedisMessageType_name, int32(x))
}

func (RedisMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type MessageLock struct {
	ComponentName        string   `protobuf:"bytes,1,opt,name=componentName,proto3" json:"componentName,omitempty"`
	LockName             string   `protobuf:"bytes,2,opt,name=lockName,proto3" json:"lockName,omitempty"`
	IsRealLock           bool     `protobuf:"varint,3,opt,name=isRealLock,proto3" json:"isRealLock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageLock) Reset()         { *m = MessageLock{} }
func (m *MessageLock) String() string { return proto.CompactTextString(m) }
func (*MessageLock) ProtoMessage()    {}
func (*MessageLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageLock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageLock.Unmarshal(m, b)
}
func (m *MessageLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageLock.Marshal(b, m, deterministic)
}
func (m *MessageLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageLock.Merge(m, src)
}
func (m *MessageLock) XXX_Size() int {
	return xxx_messageInfo_MessageLock.Size(m)
}
func (m *MessageLock) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageLock.DiscardUnknown(m)
}

var xxx_messageInfo_MessageLock proto.InternalMessageInfo

func (m *MessageLock) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *MessageLock) GetLockName() string {
	if m != nil {
		return m.LockName
	}
	return ""
}

func (m *MessageLock) GetIsRealLock() bool {
	if m != nil {
		return m.IsRealLock
	}
	return false
}

type MessageExtroInfo struct {
	ClientConnId         string         `protobuf:"bytes,1,opt,name=clientConnId,proto3" json:"clientConnId,omitempty"`
	ClientConnIp         string         `protobuf:"bytes,2,opt,name=clientConnIp,proto3" json:"clientConnIp,omitempty"`
	UserId               string         `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Locks                []*MessageLock `protobuf:"bytes,4,rep,name=locks,proto3" json:"locks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageExtroInfo) Reset()         { *m = MessageExtroInfo{} }
func (m *MessageExtroInfo) String() string { return proto.CompactTextString(m) }
func (*MessageExtroInfo) ProtoMessage()    {}
func (*MessageExtroInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageExtroInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageExtroInfo.Unmarshal(m, b)
}
func (m *MessageExtroInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageExtroInfo.Marshal(b, m, deterministic)
}
func (m *MessageExtroInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageExtroInfo.Merge(m, src)
}
func (m *MessageExtroInfo) XXX_Size() int {
	return xxx_messageInfo_MessageExtroInfo.Size(m)
}
func (m *MessageExtroInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageExtroInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageExtroInfo proto.InternalMessageInfo

func (m *MessageExtroInfo) GetClientConnId() string {
	if m != nil {
		return m.ClientConnId
	}
	return ""
}

func (m *MessageExtroInfo) GetClientConnIp() string {
	if m != nil {
		return m.ClientConnIp
	}
	return ""
}

func (m *MessageExtroInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageExtroInfo) GetLocks() []*MessageLock {
	if m != nil {
		return m.Locks
	}
	return nil
}

//定义请求结构
type HandleMessageRequest struct {
	ComponentName        string            `protobuf:"bytes,1,opt,name=componentName,proto3" json:"componentName,omitempty"`
	MethodName           string            `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MessageContent       *any.Any          `protobuf:"bytes,3,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	ExtroInfo            *MessageExtroInfo `protobuf:"bytes,4,opt,name=extroInfo,proto3" json:"extroInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandleMessageRequest) Reset()         { *m = HandleMessageRequest{} }
func (m *HandleMessageRequest) String() string { return proto.CompactTextString(m) }
func (*HandleMessageRequest) ProtoMessage()    {}
func (*HandleMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *HandleMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleMessageRequest.Unmarshal(m, b)
}
func (m *HandleMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleMessageRequest.Marshal(b, m, deterministic)
}
func (m *HandleMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleMessageRequest.Merge(m, src)
}
func (m *HandleMessageRequest) XXX_Size() int {
	return xxx_messageInfo_HandleMessageRequest.Size(m)
}
func (m *HandleMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleMessageRequest proto.InternalMessageInfo

func (m *HandleMessageRequest) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *HandleMessageRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *HandleMessageRequest) GetMessageContent() *any.Any {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

func (m *HandleMessageRequest) GetExtroInfo() *MessageExtroInfo {
	if m != nil {
		return m.ExtroInfo
	}
	return nil
}

//定义响应结构
type HandleMessageReply struct {
	MessageContent       *any.Any `protobuf:"bytes,1,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleMessageReply) Reset()         { *m = HandleMessageReply{} }
func (m *HandleMessageReply) String() string { return proto.CompactTextString(m) }
func (*HandleMessageReply) ProtoMessage()    {}
func (*HandleMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *HandleMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleMessageReply.Unmarshal(m, b)
}
func (m *HandleMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleMessageReply.Marshal(b, m, deterministic)
}
func (m *HandleMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleMessageReply.Merge(m, src)
}
func (m *HandleMessageReply) XXX_Size() int {
	return xxx_messageInfo_HandleMessageReply.Size(m)
}
func (m *HandleMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_HandleMessageReply proto.InternalMessageInfo

func (m *HandleMessageReply) GetMessageContent() *any.Any {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

type ErrorMessage struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=ErrorCode" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_InterfaceNotFound
}

func (m *ErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type PlayerInfo struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ShortId              string   `protobuf:"bytes,2,opt,name=shortId,proto3" json:"shortId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Balance              uint32   `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PlayerInfo) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetBalance() uint32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type ClientRequest struct {
	ComponentName        string   `protobuf:"bytes,1,opt,name=componentName,proto3" json:"componentName,omitempty"`
	MethodName           string   `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MessageContent       *any.Any `protobuf:"bytes,3,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *ClientRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *ClientRequest) GetMessageContent() *any.Any {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

type ClientReply struct {
	MessageName          string   `protobuf:"bytes,1,opt,name=messageName,proto3" json:"messageName,omitempty"`
	MessageContent       *any.Any `protobuf:"bytes,2,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientReply) Reset()         { *m = ClientReply{} }
func (m *ClientReply) String() string { return proto.CompactTextString(m) }
func (*ClientReply) ProtoMessage()    {}
func (*ClientReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ClientReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientReply.Unmarshal(m, b)
}
func (m *ClientReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientReply.Marshal(b, m, deterministic)
}
func (m *ClientReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientReply.Merge(m, src)
}
func (m *ClientReply) XXX_Size() int {
	return xxx_messageInfo_ClientReply.Size(m)
}
func (m *ClientReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientReply.DiscardUnknown(m)
}

var xxx_messageInfo_ClientReply proto.InternalMessageInfo

func (m *ClientReply) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *ClientReply) GetMessageContent() *any.Any {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

type LoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	ErrMessage           *ErrorMessage `protobuf:"bytes,1,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

func (m *LoginReply) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type RedisMessage struct {
	Type                 RedisMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=RedisMessageType" json:"type,omitempty"`
	Table                string           `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string           `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ValueString          string           `protobuf:"bytes,4,opt,name=valueString,proto3" json:"valueString,omitempty"`
	ValueByte            []byte           `protobuf:"bytes,5,opt,name=valueByte,proto3" json:"valueByte,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RedisMessage) Reset()         { *m = RedisMessage{} }
func (m *RedisMessage) String() string { return proto.CompactTextString(m) }
func (*RedisMessage) ProtoMessage()    {}
func (*RedisMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *RedisMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisMessage.Unmarshal(m, b)
}
func (m *RedisMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisMessage.Marshal(b, m, deterministic)
}
func (m *RedisMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisMessage.Merge(m, src)
}
func (m *RedisMessage) XXX_Size() int {
	return xxx_messageInfo_RedisMessage.Size(m)
}
func (m *RedisMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RedisMessage proto.InternalMessageInfo

func (m *RedisMessage) GetType() RedisMessageType {
	if m != nil {
		return m.Type
	}
	return RedisMessageType_SetString
}

func (m *RedisMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *RedisMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RedisMessage) GetValueString() string {
	if m != nil {
		return m.ValueString
	}
	return ""
}

func (m *RedisMessage) GetValueByte() []byte {
	if m != nil {
		return m.ValueByte
	}
	return nil
}

type MysqlAccountInfo struct {
	AutoId               uint64        `protobuf:"varint,1,opt,name=auto_id,json=autoId,proto3" json:"auto_id,omitempty"`
	Uuid                 string        `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ShortId              string        `protobuf:"bytes,3,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	Account              string        `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Password             string        `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	UpdateTime           int64         `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ErrMessage           *ErrorMessage `protobuf:"bytes,7,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MysqlAccountInfo) Reset()         { *m = MysqlAccountInfo{} }
func (m *MysqlAccountInfo) String() string { return proto.CompactTextString(m) }
func (*MysqlAccountInfo) ProtoMessage()    {}
func (*MysqlAccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *MysqlAccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlAccountInfo.Unmarshal(m, b)
}
func (m *MysqlAccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlAccountInfo.Marshal(b, m, deterministic)
}
func (m *MysqlAccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlAccountInfo.Merge(m, src)
}
func (m *MysqlAccountInfo) XXX_Size() int {
	return xxx_messageInfo_MysqlAccountInfo.Size(m)
}
func (m *MysqlAccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlAccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlAccountInfo proto.InternalMessageInfo

func (m *MysqlAccountInfo) GetAutoId() uint64 {
	if m != nil {
		return m.AutoId
	}
	return 0
}

func (m *MysqlAccountInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MysqlAccountInfo) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *MysqlAccountInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MysqlAccountInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MysqlAccountInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *MysqlAccountInfo) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

type MysqlKVMessage struct {
	TableName            string        `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	AutoId               uint64        `protobuf:"varint,2,opt,name=auto_id,json=autoId,proto3" json:"auto_id,omitempty"`
	Uuid                 string        `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ShortId              string        `protobuf:"bytes,4,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	Info                 []byte        `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	UpdateTime           int64         `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ErrMessage           *ErrorMessage `protobuf:"bytes,7,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MysqlKVMessage) Reset()         { *m = MysqlKVMessage{} }
func (m *MysqlKVMessage) String() string { return proto.CompactTextString(m) }
func (*MysqlKVMessage) ProtoMessage()    {}
func (*MysqlKVMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *MysqlKVMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlKVMessage.Unmarshal(m, b)
}
func (m *MysqlKVMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlKVMessage.Marshal(b, m, deterministic)
}
func (m *MysqlKVMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlKVMessage.Merge(m, src)
}
func (m *MysqlKVMessage) XXX_Size() int {
	return xxx_messageInfo_MysqlKVMessage.Size(m)
}
func (m *MysqlKVMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlKVMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlKVMessage proto.InternalMessageInfo

func (m *MysqlKVMessage) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *MysqlKVMessage) GetAutoId() uint64 {
	if m != nil {
		return m.AutoId
	}
	return 0
}

func (m *MysqlKVMessage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MysqlKVMessage) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

func (m *MysqlKVMessage) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MysqlKVMessage) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *MysqlKVMessage) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

type RegisterRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterReply struct {
	ErrMessage           *ErrorMessage `protobuf:"bytes,1,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

type LoadPlayerRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadPlayerRequest) Reset()         { *m = LoadPlayerRequest{} }
func (m *LoadPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*LoadPlayerRequest) ProtoMessage()    {}
func (*LoadPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *LoadPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPlayerRequest.Unmarshal(m, b)
}
func (m *LoadPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPlayerRequest.Marshal(b, m, deterministic)
}
func (m *LoadPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPlayerRequest.Merge(m, src)
}
func (m *LoadPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_LoadPlayerRequest.Size(m)
}
func (m *LoadPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPlayerRequest proto.InternalMessageInfo

func (m *LoadPlayerRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type LoadPlayerReply struct {
	ErrMessage           *ErrorMessage `protobuf:"bytes,1,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoadPlayerReply) Reset()         { *m = LoadPlayerReply{} }
func (m *LoadPlayerReply) String() string { return proto.CompactTextString(m) }
func (*LoadPlayerReply) ProtoMessage()    {}
func (*LoadPlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *LoadPlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPlayerReply.Unmarshal(m, b)
}
func (m *LoadPlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPlayerReply.Marshal(b, m, deterministic)
}
func (m *LoadPlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPlayerReply.Merge(m, src)
}
func (m *LoadPlayerReply) XXX_Size() int {
	return xxx_messageInfo_LoadPlayerReply.Size(m)
}
func (m *LoadPlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPlayerReply proto.InternalMessageInfo

func (m *LoadPlayerReply) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

func (m *LoadPlayerReply) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type NewPlayerRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ShortId              string   `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPlayerRequest) Reset()         { *m = NewPlayerRequest{} }
func (m *NewPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*NewPlayerRequest) ProtoMessage()    {}
func (*NewPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *NewPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPlayerRequest.Unmarshal(m, b)
}
func (m *NewPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPlayerRequest.Marshal(b, m, deterministic)
}
func (m *NewPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPlayerRequest.Merge(m, src)
}
func (m *NewPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_NewPlayerRequest.Size(m)
}
func (m *NewPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewPlayerRequest proto.InternalMessageInfo

func (m *NewPlayerRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *NewPlayerRequest) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

type NewPlayerReply struct {
	ErrMessage           *ErrorMessage `protobuf:"bytes,1,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewPlayerReply) Reset()         { *m = NewPlayerReply{} }
func (m *NewPlayerReply) String() string { return proto.CompactTextString(m) }
func (*NewPlayerReply) ProtoMessage()    {}
func (*NewPlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *NewPlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPlayerReply.Unmarshal(m, b)
}
func (m *NewPlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPlayerReply.Marshal(b, m, deterministic)
}
func (m *NewPlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPlayerReply.Merge(m, src)
}
func (m *NewPlayerReply) XXX_Size() int {
	return xxx_messageInfo_NewPlayerReply.Size(m)
}
func (m *NewPlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewPlayerReply proto.InternalMessageInfo

func (m *NewPlayerReply) GetErrMessage() *ErrorMessage {
	if m != nil {
		return m.ErrMessage
	}
	return nil
}

func (m *NewPlayerReply) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("RedisMessageType", RedisMessageType_name, RedisMessageType_value)
	proto.RegisterType((*MessageLock)(nil), "MessageLock")
	proto.RegisterType((*MessageExtroInfo)(nil), "MessageExtroInfo")
	proto.RegisterType((*HandleMessageRequest)(nil), "HandleMessageRequest")
	proto.RegisterType((*HandleMessageReply)(nil), "HandleMessageReply")
	proto.RegisterType((*ErrorMessage)(nil), "ErrorMessage")
	proto.RegisterType((*EmptyMessage)(nil), "EmptyMessage")
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
	proto.RegisterType((*ClientRequest)(nil), "ClientRequest")
	proto.RegisterType((*ClientReply)(nil), "ClientReply")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginReply")
	proto.RegisterType((*RedisMessage)(nil), "RedisMessage")
	proto.RegisterType((*MysqlAccountInfo)(nil), "MysqlAccountInfo")
	proto.RegisterType((*MysqlKVMessage)(nil), "MysqlKVMessage")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "RegisterReply")
	proto.RegisterType((*LoadPlayerRequest)(nil), "LoadPlayerRequest")
	proto.RegisterType((*LoadPlayerReply)(nil), "LoadPlayerReply")
	proto.RegisterType((*NewPlayerRequest)(nil), "NewPlayerRequest")
	proto.RegisterType((*NewPlayerReply)(nil), "NewPlayerReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 943 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x25, 0x5a, 0xb2, 0x46, 0xa2, 0x4c, 0x6d, 0x9c, 0x56, 0x31, 0x5a, 0x57, 0x20, 0x5a,
	0x54, 0x48, 0x51, 0x1a, 0x70, 0xaf, 0x6d, 0x01, 0x57, 0x76, 0x14, 0xa1, 0xae, 0x11, 0xac, 0xd2,
	0x5c, 0x8d, 0xb5, 0x38, 0x96, 0x09, 0x53, 0xbb, 0x0c, 0xb9, 0x4c, 0xc2, 0xef, 0x28, 0xd0, 0x5b,
	0x6f, 0xfd, 0x9b, 0x7e, 0x42, 0x2f, 0xfd, 0x94, 0x62, 0x97, 0x4b, 0x89, 0x52, 0x14, 0x24, 0x41,
	0x1b, 0x20, 0x37, 0xce, 0x9b, 0xe1, 0xec, 0xcc, 0xbc, 0x37, 0x4b, 0x82, 0xb3, 0xc0, 0x34, 0x65,
	0x73, 0xf4, 0xe3, 0x44, 0x48, 0x71, 0xf8, 0x60, 0x2e, 0xc4, 0x3c, 0xc2, 0x63, 0x6d, 0x5d, 0x67,
	0x37, 0xc7, 0x8c, 0xe7, 0x85, 0xcb, 0x13, 0xd0, 0xfe, 0xa5, 0x88, 0xbd, 0x10, 0xb3, 0x3b, 0xf2,
	0x25, 0x38, 0x33, 0xb1, 0x88, 0x05, 0x47, 0x2e, 0x2f, 0xd9, 0x02, 0xfb, 0xd6, 0xc0, 0x1a, 0xb6,
	0xe8, 0x3a, 0x48, 0x0e, 0x61, 0x2f, 0x12, 0xb3, 0x3b, 0x1d, 0x50, 0xd3, 0x01, 0x4b, 0x9b, 0x1c,
	0x01, 0x84, 0x29, 0x45, 0x16, 0xa9, 0x7c, 0xfd, 0xfa, 0xc0, 0x1a, 0xee, 0xd1, 0x0a, 0xe2, 0xfd,
	0x6e, 0x81, 0x6b, 0x4e, 0x3c, 0x7f, 0x25, 0x13, 0x31, 0xe1, 0x37, 0x82, 0x78, 0xd0, 0x99, 0x45,
	0x21, 0x72, 0x39, 0x12, 0x9c, 0x4f, 0x02, 0x73, 0xea, 0x1a, 0xb6, 0x11, 0x13, 0x9b, 0x83, 0xd7,
	0x30, 0xf2, 0x09, 0x34, 0xb2, 0x14, 0x93, 0x49, 0xa0, 0x0f, 0x6e, 0x51, 0x63, 0x11, 0x0f, 0x76,
	0x55, 0x81, 0x69, 0xdf, 0x1e, 0xd4, 0x87, 0xed, 0x93, 0x8e, 0x5f, 0xe9, 0x99, 0x16, 0x2e, 0xef,
	0x2f, 0x0b, 0x0e, 0x1e, 0x33, 0x1e, 0x44, 0x68, 0x9c, 0x14, 0x9f, 0x67, 0x98, 0xca, 0x77, 0x9c,
	0xc9, 0x11, 0xc0, 0x02, 0xe5, 0xad, 0x08, 0x2a, 0x53, 0xa9, 0x20, 0xe4, 0x7b, 0xe8, 0x1a, 0x52,
	0x46, 0x82, 0x4b, 0xe4, 0x52, 0x97, 0xd8, 0x3e, 0x39, 0xf0, 0x0b, 0x72, 0xfc, 0x92, 0x1c, 0xff,
	0x94, 0xe7, 0x74, 0x23, 0x96, 0x1c, 0x43, 0x0b, 0xcb, 0x69, 0xf5, 0x6d, 0xfd, 0x62, 0xcf, 0xdf,
	0x1c, 0x23, 0x5d, 0xc5, 0x78, 0x14, 0xc8, 0x46, 0x33, 0x71, 0x94, 0x6f, 0x29, 0xc2, 0x7a, 0xf7,
	0x22, 0xbc, 0xc7, 0xd0, 0x39, 0x4f, 0x12, 0x91, 0x98, 0x94, 0xe4, 0x08, 0xec, 0x99, 0x08, 0x8a,
	0x79, 0x74, 0x4f, 0xc0, 0xd7, 0xce, 0x91, 0x08, 0x90, 0x6a, 0x9c, 0xf4, 0xa1, 0x69, 0x32, 0x98,
	0x79, 0x94, 0xa6, 0xd7, 0x85, 0xce, 0xf9, 0x22, 0x96, 0xb9, 0xc9, 0xe4, 0xdd, 0x02, 0x3c, 0x89,
	0x58, 0x8e, 0x89, 0x56, 0x03, 0x01, 0x3b, 0xcb, 0xc2, 0x52, 0x05, 0xfa, 0x59, 0xe5, 0x4a, 0x6f,
	0x45, 0x22, 0x27, 0x41, 0x99, 0xcb, 0x98, 0x2a, 0x9a, 0xab, 0x91, 0x17, 0x8c, 0xeb, 0x67, 0x15,
	0x7d, 0xcd, 0x22, 0xc6, 0x67, 0xa8, 0x87, 0xe5, 0xd0, 0xd2, 0xf4, 0x7e, 0xb3, 0xc0, 0x19, 0x69,
	0xc9, 0x7c, 0x44, 0xf4, 0x7a, 0x0b, 0x68, 0x97, 0x45, 0x29, 0x9a, 0x06, 0xd0, 0x36, 0x01, 0x95,
	0x82, 0xaa, 0xd0, 0x96, 0xe3, 0x6a, 0xef, 0x71, 0xdc, 0x19, 0x74, 0x2e, 0xc4, 0x3c, 0xe4, 0xe5,
	0x08, 0xfa, 0xd0, 0x64, 0xb3, 0x99, 0xc8, 0x8c, 0x1e, 0x5a, 0xb4, 0x34, 0xd5, 0xa6, 0xc7, 0x2c,
	0x4d, 0x5f, 0x8a, 0xa4, 0x9c, 0xfb, 0xd2, 0x56, 0xa4, 0x99, 0x2c, 0xaa, 0xe6, 0x6f, 0x01, 0x30,
	0x29, 0xa5, 0x61, 0x64, 0xe5, 0xf8, 0x55, 0xbd, 0xd0, 0x4a, 0x00, 0xf9, 0x06, 0x20, 0x5e, 0x32,
	0x6e, 0x8a, 0x6f, 0xfb, 0x2b, 0x11, 0xd0, 0x8a, 0xdb, 0xfb, 0xc3, 0x82, 0x0e, 0xc5, 0x20, 0x4c,
	0xcb, 0xb7, 0xbf, 0x02, 0x5b, 0xe6, 0x71, 0xa9, 0xbc, 0x9e, 0x5f, 0x75, 0x3e, 0xcd, 0x63, 0xa4,
	0xda, 0x4d, 0x0e, 0x60, 0x57, 0xb2, 0xeb, 0xa8, 0xe4, 0xab, 0x30, 0x88, 0x0b, 0xf5, 0x3b, 0xcc,
	0x8d, 0x5e, 0xd4, 0xa3, 0x9a, 0xf7, 0x0b, 0x16, 0x65, 0x38, 0x95, 0x49, 0xc8, 0xe7, 0x5a, 0x32,
	0x2d, 0x5a, 0x85, 0xc8, 0x67, 0xd0, 0xd2, 0xe6, 0x4f, 0xb9, 0xc4, 0xfe, 0xee, 0xc0, 0x1a, 0x76,
	0xe8, 0x0a, 0xf0, 0xfe, 0x51, 0x77, 0x5a, 0x9e, 0x3e, 0x8f, 0x4e, 0x8b, 0xb1, 0x69, 0x15, 0x7f,
	0x0a, 0x4d, 0x96, 0x49, 0x71, 0x65, 0x84, 0x6c, 0xd3, 0x86, 0x32, 0x0b, 0xc1, 0x6a, 0x79, 0xd7,
	0x2a, 0xf2, 0x7e, 0x00, 0x7b, 0x5a, 0xcf, 0x2a, 0xba, 0xbe, 0xae, 0xef, 0x0a, 0x39, 0xf6, 0x9b,
	0xc9, 0xd9, 0x5d, 0x27, 0x87, 0x7c, 0x01, 0xed, 0x2c, 0x0e, 0x98, 0xc4, 0x2b, 0x19, 0x2e, 0xb0,
	0xdf, 0x18, 0x58, 0xc3, 0x3a, 0x85, 0x02, 0x7a, 0x1a, 0x2e, 0x70, 0x83, 0xaf, 0xe6, 0x5b, 0xf8,
	0xf2, 0xfe, 0xb6, 0xa0, 0xab, 0x5b, 0xfc, 0xf9, 0x59, 0x49, 0xc2, 0xe7, 0x00, 0x7a, 0xa0, 0x57,
	0x7c, 0x25, 0xd2, 0x96, 0x46, 0xb4, 0x44, 0x2b, 0xfd, 0xd7, 0xb6, 0xf6, 0x5f, 0x7f, 0x43, 0xff,
	0xf6, 0x6b, 0xfb, 0x1d, 0x2a, 0x8d, 0x14, 0x53, 0xd7, 0xcf, 0xff, 0x7b, 0x77, 0x63, 0xd8, 0xa7,
	0x38, 0x0f, 0x53, 0x89, 0xc9, 0x7f, 0xdb, 0x89, 0x1f, 0xc1, 0x59, 0x25, 0x7a, 0xff, 0xb5, 0xf0,
	0xbe, 0x86, 0xde, 0x85, 0x60, 0x41, 0xb1, 0x07, 0x65, 0x29, 0x5b, 0xee, 0x43, 0x6f, 0x01, 0xfb,
	0xd5, 0xc0, 0x0f, 0xbd, 0x81, 0xa7, 0xe0, 0x5e, 0xe2, 0xcb, 0xb7, 0x96, 0xb5, 0xc6, 0xe3, 0xfa,
	0x3d, 0xed, 0x45, 0xd0, 0xad, 0xa4, 0xf8, 0xc0, 0x05, 0x3f, 0xfc, 0xd3, 0x82, 0xd6, 0xf2, 0x7b,
	0x44, 0xee, 0x43, 0x6f, 0xc2, 0x25, 0x26, 0x37, 0x6c, 0x86, 0x97, 0x42, 0x3e, 0x12, 0x19, 0x0f,
	0xdc, 0x1d, 0x72, 0x0f, 0xf6, 0xcd, 0xc6, 0x2e, 0x41, 0x8b, 0xb8, 0xd0, 0x31, 0xe0, 0xf9, 0xab,
	0x30, 0x95, 0x6e, 0x4d, 0x21, 0x67, 0x4c, 0xb2, 0x65, 0x4c, 0x9d, 0x38, 0xd0, 0x52, 0x48, 0x11,
	0x60, 0x93, 0x1e, 0x38, 0x63, 0xe4, 0xbf, 0x66, 0x61, 0xf0, 0x88, 0x85, 0x11, 0x06, 0xee, 0x2e,
	0x39, 0x00, 0x77, 0x8c, 0x7c, 0x5a, 0xf4, 0x6e, 0xd0, 0x06, 0xd9, 0x87, 0xf6, 0x14, 0x93, 0x17,
	0x98, 0xe8, 0xd2, 0xdc, 0xe6, 0xc3, 0x67, 0xe0, 0x6e, 0xde, 0x5d, 0x2a, 0xf9, 0x14, 0x65, 0x71,
	0xf1, 0xb8, 0x3b, 0xa4, 0x0d, 0xcd, 0x29, 0x4a, 0x75, 0xcf, 0xb8, 0x96, 0xf2, 0x8d, 0x97, 0xbe,
	0x9a, 0xf2, 0x8d, 0x8d, 0xaf, 0x4e, 0x00, 0x1a, 0x67, 0x18, 0xa1, 0x44, 0xd7, 0x3e, 0xb9, 0x04,
	0x67, 0x4c, 0x9f, 0x8c, 0x46, 0xe5, 0x37, 0x8c, 0xfc, 0x00, 0xce, 0xda, 0xff, 0x00, 0xb9, 0xef,
	0x6f, 0xfb, 0xd9, 0x39, 0xbc, 0xe7, 0xbf, 0xfe, 0xdb, 0xe0, 0xed, 0x5c, 0x37, 0xf4, 0xf7, 0xe4,
	0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x76, 0x25, 0x44, 0x94, 0x59, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GRPCComponentClient is the client API for GRPCComponent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCComponentClient interface {
	//定义服务中的方法
	HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageReply, error)
}

type gRPCComponentClient struct {
	cc *grpc.ClientConn
}

func NewGRPCComponentClient(cc *grpc.ClientConn) GRPCComponentClient {
	return &gRPCComponentClient{cc}
}

func (c *gRPCComponentClient) HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageReply, error) {
	out := new(HandleMessageReply)
	err := c.cc.Invoke(ctx, "/GRPCComponent/HandleMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCComponentServer is the server API for GRPCComponent service.
type GRPCComponentServer interface {
	//定义服务中的方法
	HandleMessage(context.Context, *HandleMessageRequest) (*HandleMessageReply, error)
}

// UnimplementedGRPCComponentServer can be embedded to have forward compatible implementations.
type UnimplementedGRPCComponentServer struct {
}

func (*UnimplementedGRPCComponentServer) HandleMessage(ctx context.Context, req *HandleMessageRequest) (*HandleMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMessage not implemented")
}

func RegisterGRPCComponentServer(s *grpc.Server, srv GRPCComponentServer) {
	s.RegisterService(&_GRPCComponent_serviceDesc, srv)
}

func _GRPCComponent_HandleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCComponentServer).HandleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GRPCComponent/HandleMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCComponentServer).HandleMessage(ctx, req.(*HandleMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCComponent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GRPCComponent",
	HandlerType: (*GRPCComponentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMessage",
			Handler:    _GRPCComponent_HandleMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
